import Header from "@/app/components/layout/header";
import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const sevillana = Merriweather({
	subsets: ["latin"],
	weight: ["400"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<Script
					async
					src="https://www.googletagmanager.com/gtag/js?id=G-4LWTT7DZYW"
				></Script>
				<Script id="tagmanager">
					{`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('set', {cookie_flags: 'SameSite=None;Secure'});
            gtag('set', {cookie_domain: '${
							new URL(process.env.NEXT_SITE_URL).hostname
						}'});

            gtag('config', '${process.env.NEXT_PUBLIC_MEASUREMENT_ID}');
          `}
				</Script>
			</head>
			<body className={`${sevillana.className} antialiased`}>
				<Header />
				<main className="max-w-[1280px] mx-auto pt-10 px-6">{children}</main>
			</body>
		</html>
	);
}
